version: '3'

services:
  payload:
    image: node:18-alpine
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "yarn install && yarn dev"
    depends_on:
      - mongo
    env_file:
      - .env

  cms:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      DATABASE_URI: mongodb+srv://ndquang5802:UBWskx677259ZChD@local-dev.olruujo.mongodb.net/resume
      PAYLOAD_SECRET: 48aadc13ff2e1db537bc6725
      CLOUDINARY_CLOUD_NAME: dvvlgmxvi
      CLOUDINARY_API_KEY: 329439887783116
      CLOUDINARY_API_SECRET: sqLeNdTq5WNCVOSCqi9ltUCP1WE

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    logging:
      driver: none

volumes:
  data:
  node_modules:
